### ISSUE TITLE
Not showing up in HACS

### ISSUE THREAD

**Issue by dkgof** [jnxxx/homeassistant-connectedcars_io#2]
I can't find this integration in HACS right now.

**Comment by jnxxx** [comment]
I planned to upload it... but it failed to validate because there were no connected cars icon in the brands repository.
I tried to add that icon, but had to validate I owned the rights to it and would grant Home Assistant to use it (or something like that).
Well, I do not own the rights to the logo. So, I dropped it.

If you want, you can add the repository as a custom repository.
Go to HACS / Integrations / click the three dots and then Custom repositories.

**Comment by dkgof** [comment]
Thanks that worked, did not know about the custom repo setting.
